### ISSUE TITLE
No documentation can be found

### ISSUE THREAD

**Issue by Heiko-san** [photom/mod_socache_redis#3]
Hi,

unfortunately I can't find any email address nor any documentation for this project.
We plan to use this module in a production environment using apache 2.4 on a fedora like plattfrom.
Is there any documentation to help us install and configure this module?
Or could you provide us a way to directly communicate with you about the projects details?

**Comment by diovoemor** [comment]
It's in the comments at the top of mod_socache_redis.c

**Comment by photom** [comment]
Sorry for late replying.
As diovoemor said, please check mod_socache_redis.c .
And build.sh is an example build procedure.
If you have a question, please open a issue like this.
